### ISSUE TITLE
Linear Model Data

### ISSUE THREAD

**Issue by TimiH** [tobiasemrich/SchafkopfRL#6]
Hi,
I am building a similiar project to yours (https://github.com/TimiH/Schafkopf) and used your PPO and trainings structure, but having trouble converging a Linear model. I saw that there is no data for the Linear model. Is there a reason for that? Did you experiment with the parameters and can give me advice?
Regards Tim

**Comment by tobiasemrich** [comment]
Hi Tim,

that's great! The parameters I used for the linear model are in the readme (lr = 0.002, update every 100K games, batch_size = 600K, c1 = 0.5, c2 = 0.005, steps = 15M). That was however on a large memory GPU. I have not trained it for quite some time and made some changes in between, so I can not guarantee that it will work out of the box. In the meantime I figured that that the network has way more parameters than necessary, so you might want to get rid of some layers and also use smaller size fc layers. In addition increasing batchsize always helps with convergence.

**Comment by TimiH** [comment]
Thank you for your answer. Yeah I am starting to get a feeling for the batch_size effect. One questions though: Isn't the batch size directly influenced by the update_Games, since the len(Dataset) = update_games * 4 players * 8 observations? Because I saw that you multiply update_Games by the seemingly arbitrary 22. Maybe I am understanding something wrong though.
Have you thought about only collecting samples from one player to avoid correlation within the dataset?

**Comment by tobiasemrich** [comment]
In my case there are 11 (1 bidding, 2 contra, 8 tricks) observations per player per game. That means the size of the training dataset is 44 * update_games (==maximum possible batch_size). Thus, 22 * update_games just means two batches, but I think this was just the maximum that my GPU could handle. I think it is actually a bad idea to make it dependent on update_games, rather you want to make this as large as possible.

Collecting data from one player only is certainly more sound, but I was not willing to throw away 3/4 of the games. I believe it does not make a big difference, but I may very well be wrong.

**Comment by TimiH** [comment]
You are the GOAT!!!! Thank you so much.
Discounting rewards was my problem, and batch_size is actually not that important. I reduced the layers(input ->hidden->ouput), layersize(48), and  can achieve decent results for my baselines even with sizes around 8k.  
Training seperate neworks for each mode (Team,Wenz,Solo) also looks promising! Have not tried the approach of using 3/4 of games and I tend to agree with your assesment.
Again thanks a lot.
